services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=runfit'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=runfit'
    ports:
      - '3307:3306'