spring:
  datasource:
    url: jdbc:mysql://localhost:3307/runfit
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  docker:
    compose:
      lifecycle-management: start_only

jwt:
  access:
    secret: localtest-dev-jwt-access-secret-key
    expiration: 3600000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace